### ISSUE TITLE
Zooming, brightness/contrast

### ISSUE THREAD

**Issue by thomaskuestner** [thomaskuestner/CNNArt#23]
Mouse button actions:
Zooming on pressed right mouse button
Brightness/contrast adjustment on pressed middle mouse button

**Comment by ZiweiWU713** [comment]
@thomaskuestner  I have finished these functions with PyQt5. For zooming I use mouse wheel instead of right click, it's easier to focus on some specific point and also reduces the possibility of wrong click. I will integrate these functions into my GUI after I finish flexible grid viewing. You can try it then.

**Comment by thomaskuestner** [comment]
Please use the following mouse clicks:
left: move
middle: brightness and contrast
right: zoom
mouse wheel: scrolling through slices

**Comment by ZiweiWU713** [comment]
@thomaskuestner  I have finished these functions. I think I can also finish the design of flexible grids viewing this week. Then I will upload my new code.
