### ISSUE TITLE
Check Python compatibility

### ISSUE THREAD

**Issue by thomaskuestner** [thomaskuestner/CNNArt#28]
check if code runs under python 3.5 -> determines PyQt version

**Comment by TokenJan** [comment]
I've tested the code under my own pc with python 3.5.2, but there are some conditions not compatible.

1. parentheses should be added in `print` function
e.g. `print "Load data" ` => `print("Load data")`

2. `xrange` should be replaced with `range`

3. in the following code, build-in function `next(reader)` should be used and the file should be open with text (`"r"`) instead of byte (`"rb"`)
```
        ifile = open('config'+os.sep+'database'+os.sep+self.sDatabase+'.csv',"rb") # config file must exist for database!
        reader = csv.reader(ifile)
        reader.next()
```

4. following code only works in python2
```
cnnModel = __import__(sModel, globals(), locals(), ['createModel', 'fTrain', 'fPredict'], -1)  # dynamic module loading with specified functions and with relative implict importing (level=-1) -> only in Python2
```

Shall we adapt these changes and make it compatible in both python2 and python3?

**Comment by thomaskuestner** [comment]
@TokenJan Thanks for the test.
1. This should be easily fixed
2. Can also be replaced without any expected downsides
3. Ok, can be changed
4. I was expecting this mismatch, because this dynamic loading trick is only supported till python2.7. However, we may still use this code fragment which can be revised for python3 as:
`cnnModel = __import__(sModel, globals(), locals(), ['createModel', 'fTrain', 'fPredict'], 0)`
We have to verify if this still works in python2 and python3 - I want to omit (if possible) a version dependent loading behaviour.

**Comment by ywlhlm** [comment]
Hi everyone, 
there is also a Python 3 problem in DataPreprocessing.py at the line
`loadMark = shelve.open('..' + os.sep + 'Markings' + os.sep + proband + '.slv')`

I guess the problem is that Python2 creates with `shelve`  a single  '***.slv' file and 
Python3 creates 3 much smaller files:
  '***.slv.dir'
  '***.slv.dat'
  '***.slv.bak'
Therefore the following error occurs under Pyhton 3.5.4: dbm.error: db type could not be determined.

Does anyone have idea to solve that? Or how are the Marking files in the Markings directory generated so that we can reproduce them with Python 3?

There is stackoverflow topic of converting the slv-files using another underlying database:
https://stackoverflow.com/questions/27493733/use-python-2-shelf-in-python-3

But this solution did not work for me yet.

Thank you!

**Comment by thomaskuestner** [comment]
@SebastianMilde Please have a look at the markings loading

**Comment by SebastianMilde** [comment]
Hi everyone,
srry that i couldn't answer the questions. I had a lot of to do with my thesis.
At the beginning of my thesis i checked my code in Python 3.5 and Python 3.6 and it worked. I used the os Windows10. The only problem was the expression 'has_key', because has_key was removed in Python3.  So i changed the expression to 'key in nameofdictionary' for Python3. If there is any problem with shelve files, maybe we can use the package h5py for saving the data. @TokenJan maybe you can show me this error on your PC this week, so we can fix it together.

**Comment by thomaskuestner** [comment]
Problem solved via https://github.com/thomaskuestner/CNNArt/commit/9651c929c51a0b7e955dbab9894a83b1c78bd752
Markings are stored now in JSON
